apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # it is importtant if we want your app can get traffic from service
   h: plabel1 #label always be key value pair, must be unique
  name: pod1 #must be unique
spec:
  containers:
  - image: nginx
    name: pod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
